window.esdocSearchIndex = [
  [
    "nrser/src/errors/baseerror.js~baseerror",
    "function/index.html#static-function-BaseError",
    "<span>BaseError</span> <span class=\"search-result-import-path\">nrser/src/errors/BaseError.js</span>",
    "function"
  ],
  [
    "nrser/src/env.js~default_env",
    "variable/index.html#static-variable-DEFAULT_ENV",
    "<span>DEFAULT_ENV</span> <span class=\"search-result-import-path\">nrser/src/env.js</span>",
    "variable"
  ],
  [
    "nrser/src/metalogger/index.js~default_logger",
    "variable/index.html#static-variable-DEFAULT_LOGGER",
    "<span>DEFAULT_LOGGER</span> <span class=\"search-result-import-path\">nrser/src/metalogger/index.js</span>",
    "variable"
  ],
  [
    "nrser/src/deferred.js~deferred",
    "class/src/Deferred.js~Deferred.html",
    "<span>Deferred</span> <span class=\"search-result-import-path\">nrser/src/Deferred.js</span>",
    "class"
  ],
  [
    "nrser/src/testing/describer.js~describer",
    "class/src/testing/Describer.js~Describer.html",
    "<span>Describer</span> <span class=\"search-result-import-path\">nrser/src/testing/Describer.js</span>",
    "class"
  ],
  [
    "nrser/src/types/index.js~empty",
    "variable/index.html#static-variable-Empty",
    "<span>Empty</span> <span class=\"search-result-import-path\">nrser/src/types/index.js</span>",
    "variable"
  ],
  [
    "nrser/src/types/index.js~errortype",
    "variable/index.html#static-variable-ErrorType",
    "<span>ErrorType</span> <span class=\"search-result-import-path\">nrser/src/types/index.js</span>",
    "variable"
  ],
  [
    "nrser/src/testing/index.js~expect",
    "class/src/testing/index.js~Expect.html",
    "<span>Expect</span> <span class=\"search-result-import-path\">nrser/src/testing/index.js</span>",
    "class"
  ],
  [
    "nrser/src/string.js~i",
    "variable/index.html#static-variable-I",
    "<span>I</span> <span class=\"search-result-import-path\">nrser/src/string.js</span>",
    "variable"
  ],
  [
    "nrser/src/env.js~is_browser",
    "variable/index.html#static-variable-IS_BROWSER",
    "<span>IS_BROWSER</span> <span class=\"search-result-import-path\">nrser/src/env.js</span>",
    "variable"
  ],
  [
    "nrser/src/env.js~is_node",
    "variable/index.html#static-variable-IS_NODE",
    "<span>IS_NODE</span> <span class=\"search-result-import-path\">nrser/src/env.js</span>",
    "variable"
  ],
  [
    "nrser/src/string.js~jsontag",
    "variable/index.html#static-variable-JSONTag",
    "<span>JSONTag</span> <span class=\"search-result-import-path\">nrser/src/string.js</span>",
    "variable"
  ],
  [
    "nrser/src/errors/keyerror.js~keyerror",
    "class/src/errors/KeyError.js~KeyError.html",
    "<span>KeyError</span> <span class=\"search-result-import-path\">nrser/src/errors/KeyError.js</span>",
    "class"
  ],
  [
    "nrser/src/metalogger/level.js~level_name_pad_length",
    "variable/index.html#static-variable-LEVEL_NAME_PAD_LENGTH",
    "<span>LEVEL_NAME_PAD_LENGTH</span> <span class=\"search-result-import-path\">nrser/src/metalogger/Level.js</span>",
    "variable"
  ],
  [
    "nrser/src/metalogger/level.js~level",
    "class/src/metalogger/Level.js~Level.html",
    "<span>Level</span> <span class=\"search-result-import-path\">nrser/src/metalogger/Level.js</span>",
    "class"
  ],
  [
    "nrser/src/metalogger/levelspec.js~levelspec",
    "class/src/metalogger/LevelSpec.js~LevelSpec.html",
    "<span>LevelSpec</span> <span class=\"search-result-import-path\">nrser/src/metalogger/LevelSpec.js</span>",
    "class"
  ],
  [
    "nrser/src/metalogger/logger.js~logger",
    "class/src/metalogger/Logger.js~Logger.html",
    "<span>Logger</span> <span class=\"search-result-import-path\">nrser/src/metalogger/Logger.js</span>",
    "class"
  ],
  [
    "nrser/src/errors/matcherror.js~matcherror",
    "class/src/errors/MatchError.js~MatchError.html",
    "<span>MatchError</span> <span class=\"search-result-import-path\">nrser/src/errors/MatchError.js</span>",
    "class"
  ],
  [
    "nrser/src/errors/notfounderror.js~notfounderror",
    "class/src/errors/NotFoundError.js~NotFoundError.html",
    "<span>NotFoundError</span> <span class=\"search-result-import-path\">nrser/src/errors/NotFoundError.js</span>",
    "class"
  ],
  [
    "nrser/src/errors/notimplementederror.js~notimplementederror",
    "class/src/errors/NotImplementedError.js~NotImplementedError.html",
    "<span>NotImplementedError</span> <span class=\"search-result-import-path\">nrser/src/errors/NotImplementedError.js</span>",
    "class"
  ],
  [
    "nrser/src/errors/nrsererror.js~nrsererror",
    "class/src/errors/NrserError.js~NrserError.html",
    "<span>NrserError</span> <span class=\"search-result-import-path\">nrser/src/errors/NrserError.js</span>",
    "class"
  ],
  [
    "nrser/src/types/index.js~null",
    "variable/index.html#static-variable-Null",
    "<span>Null</span> <span class=\"search-result-import-path\">nrser/src/types/index.js</span>",
    "variable"
  ],
  [
    "nrser/src/types/index.js~promisetype",
    "variable/index.html#static-variable-PromiseType",
    "<span>PromiseType</span> <span class=\"search-result-import-path\">nrser/src/types/index.js</span>",
    "variable"
  ],
  [
    "nrser/src/metalogger/snapshot.js~snapshot_ref",
    "class/src/metalogger/snapshot.js~SNAPSHOT_REF.html",
    "<span>SNAPSHOT_REF</span> <span class=\"search-result-import-path\">nrser/src/metalogger/snapshot.js</span>",
    "class"
  ],
  [
    "nrser/src/errors/stateerror.js~stateerror",
    "class/src/errors/StateError.js~StateError.html",
    "<span>StateError</span> <span class=\"search-result-import-path\">nrser/src/errors/StateError.js</span>",
    "class"
  ],
  [
    "nrser/src/types/index.js~undefined",
    "variable/index.html#static-variable-Undefined",
    "<span>Undefined</span> <span class=\"search-result-import-path\">nrser/src/types/index.js</span>",
    "variable"
  ],
  [
    "nrser/src/errors/valueerror.js~valueerror",
    "class/src/errors/ValueError.js~ValueError.html",
    "<span>ValueError</span> <span class=\"search-result-import-path\">nrser/src/errors/ValueError.js</span>",
    "class"
  ],
  [
    "nrser/src/path.js~absolute",
    "variable/index.html#static-variable-absolute",
    "<span>absolute</span> <span class=\"search-result-import-path\">nrser/src/path.js</span>",
    "variable"
  ],
  [
    "nrser/src/env.js~appinstance",
    "function/index.html#static-function-appInstance",
    "<span>appInstance</span> <span class=\"search-result-import-path\">nrser/src/env.js</span>",
    "function"
  ],
  [
    "nrser/src/array.js~asarray",
    "function/index.html#static-function-asArray",
    "<span>asArray</span> <span class=\"search-result-import-path\">nrser/src/array.js</span>",
    "function"
  ],
  [
    "nrser/src/object.js~assemble",
    "function/index.html#static-function-assemble",
    "<span>assemble</span> <span class=\"search-result-import-path\">nrser/src/object.js</span>",
    "function"
  ],
  [
    "nrser/src/path.js~commonbase",
    "function/index.html#static-function-commonBase",
    "<span>commonBase</span> <span class=\"search-result-import-path\">nrser/src/path.js</span>",
    "function"
  ],
  [
    "nrser/src/string.js~commonprefix",
    "function/index.html#static-function-commonPrefix",
    "<span>commonPrefix</span> <span class=\"search-result-import-path\">nrser/src/string.js</span>",
    "function"
  ],
  [
    "nrser/src/string.js~deindent",
    "function/index.html#static-function-deindent",
    "<span>deindent</span> <span class=\"search-result-import-path\">nrser/src/string.js</span>",
    "function"
  ],
  [
    "nrser/src/array.js~eachasarray",
    "function/index.html#static-function-eachAsArray",
    "<span>eachAsArray</span> <span class=\"search-result-import-path\">nrser/src/array.js</span>",
    "function"
  ],
  [
    "nrser/src/env.js~env",
    "function/index.html#static-function-env",
    "<span>env</span> <span class=\"search-result-import-path\">nrser/src/env.js</span>",
    "function"
  ],
  [
    "nrser/src/path.js~expand",
    "function/index.html#static-function-expand",
    "<span>expand</span> <span class=\"search-result-import-path\">nrser/src/path.js</span>",
    "function"
  ],
  [
    "nrser/src/path.js~expanddir",
    "function/index.html#static-function-expandDir",
    "<span>expandDir</span> <span class=\"search-result-import-path\">nrser/src/path.js</span>",
    "function"
  ],
  [
    "nrser/src/types/struct.js~extendprops",
    "function/index.html#static-function-extendProps",
    "<span>extendProps</span> <span class=\"search-result-import-path\">nrser/src/types/struct.js</span>",
    "function"
  ],
  [
    "nrser/src/string.js~findcommonindent",
    "function/index.html#static-function-findCommonIndent",
    "<span>findCommonIndent</span> <span class=\"search-result-import-path\">nrser/src/string.js</span>",
    "function"
  ],
  [
    "nrser/src/collection.js~findonly",
    "function/index.html#static-function-findOnly",
    "<span>findOnly</span> <span class=\"search-result-import-path\">nrser/src/collection.js</span>",
    "function"
  ],
  [
    "nrser/src/fs.js~fs",
    "variable/index.html#static-variable-fs",
    "<span>fs</span> <span class=\"search-result-import-path\">nrser/src/fs.js</span>",
    "variable"
  ],
  [
    "nrser/src/object.js~groupbyeach",
    "function/index.html#static-function-groupByEach",
    "<span>groupByEach</span> <span class=\"search-result-import-path\">nrser/src/object.js</span>",
    "function"
  ],
  [
    "nrser/src/string.js~indent",
    "function/index.html#static-function-indent",
    "<span>indent</span> <span class=\"search-result-import-path\">nrser/src/string.js</span>",
    "function"
  ],
  [
    "nrser/src/object.js~insert",
    "function/index.html#static-function-insert",
    "<span>insert</span> <span class=\"search-result-import-path\">nrser/src/object.js</span>",
    "function"
  ],
  [
    "nrser/src/string.js~inspect",
    "variable/index.html#static-variable-inspect",
    "<span>inspect</span> <span class=\"search-result-import-path\">nrser/src/string.js</span>",
    "variable"
  ],
  [
    "nrser/src/types/index.js~instanceof",
    "function/index.html#static-function-instanceOf",
    "<span>instanceOf</span> <span class=\"search-result-import-path\">nrser/src/types/index.js</span>",
    "function"
  ],
  [
    "nrser/src/env.js~isbrowser",
    "variable/index.html#static-variable-isBrowser",
    "<span>isBrowser</span> <span class=\"search-result-import-path\">nrser/src/env.js</span>",
    "variable"
  ],
  [
    "nrser/src/fs.js~isdir",
    "function/index.html#static-function-isDir",
    "<span>isDir</span> <span class=\"search-result-import-path\">nrser/src/fs.js</span>",
    "function"
  ],
  [
    "nrser/src/fs.js~isdirsync",
    "function/index.html#static-function-isDirSync",
    "<span>isDirSync</span> <span class=\"search-result-import-path\">nrser/src/fs.js</span>",
    "function"
  ],
  [
    "nrser/src/env.js~isnode",
    "variable/index.html#static-variable-isNode",
    "<span>isNode</span> <span class=\"search-result-import-path\">nrser/src/env.js</span>",
    "variable"
  ],
  [
    "nrser/src/string.js~iswhitespace",
    "function/index.html#static-function-isWhitespace",
    "<span>isWhitespace</span> <span class=\"search-result-import-path\">nrser/src/string.js</span>",
    "function"
  ],
  [
    "nrser/src/testing/index.js~itmaps",
    "function/index.html#static-function-itMaps",
    "<span>itMaps</span> <span class=\"search-result-import-path\">nrser/src/testing/index.js</span>",
    "function"
  ],
  [
    "nrser/src/string.js~j",
    "variable/index.html#static-variable-j",
    "<span>j</span> <span class=\"search-result-import-path\">nrser/src/string.js</span>",
    "variable"
  ],
  [
    "nrser/src/string.js~leadingwhitespace",
    "function/index.html#static-function-leadingWhitespace",
    "<span>leadingWhitespace</span> <span class=\"search-result-import-path\">nrser/src/string.js</span>",
    "function"
  ],
  [
    "nrser/src/string.js~lines",
    "function/index.html#static-function-lines",
    "<span>lines</span> <span class=\"search-result-import-path\">nrser/src/string.js</span>",
    "function"
  ],
  [
    "nrser/src/array.js~mapasarray",
    "function/index.html#static-function-mapAsArray",
    "<span>mapAsArray</span> <span class=\"search-result-import-path\">nrser/src/array.js</span>",
    "function"
  ],
  [
    "nrser/src/collection.js~mapdefined",
    "function/index.html#static-function-mapDefined",
    "<span>mapDefined</span> <span class=\"search-result-import-path\">nrser/src/collection.js</span>",
    "function"
  ],
  [
    "nrser/src/object.js~mapdefinedvalues",
    "function/index.html#static-function-mapDefinedValues",
    "<span>mapDefinedValues</span> <span class=\"search-result-import-path\">nrser/src/object.js</span>",
    "function"
  ],
  [
    "nrser/src/match.js~match",
    "function/index.html#static-function-match",
    "<span>match</span> <span class=\"search-result-import-path\">nrser/src/match.js</span>",
    "function"
  ],
  [
    "nrser/src/object.js~need",
    "function/index.html#static-function-need",
    "<span>need</span> <span class=\"search-result-import-path\">nrser/src/object.js</span>",
    "function"
  ],
  [
    "nrser/src/types/list.js~nonemptylist",
    "function/index.html#static-function-nonEmptyList",
    "<span>nonEmptyList</span> <span class=\"search-result-import-path\">nrser/src/types/list.js</span>",
    "function"
  ],
  [
    "nrser/src/string.js~nonwhitespacelines",
    "function/index.html#static-function-nonWhitespaceLines",
    "<span>nonWhitespaceLines</span> <span class=\"search-result-import-path\">nrser/src/string.js</span>",
    "function"
  ],
  [
    "nrser/src/types/index.js~nullable",
    "function/index.html#static-function-nullable",
    "<span>nullable</span> <span class=\"search-result-import-path\">nrser/src/types/index.js</span>",
    "function"
  ],
  [
    "nrser/src/string.js~pad",
    "function/index.html#static-function-pad",
    "<span>pad</span> <span class=\"search-result-import-path\">nrser/src/string.js</span>",
    "function"
  ],
  [
    "nrser/src/object.js~procure",
    "function/index.html#static-function-procure",
    "<span>procure</span> <span class=\"search-result-import-path\">nrser/src/object.js</span>",
    "function"
  ],
  [
    "nrser/src/path.js~resolvedir",
    "function/index.html#static-function-resolveDir",
    "<span>resolveDir</span> <span class=\"search-result-import-path\">nrser/src/path.js</span>",
    "function"
  ],
  [
    "nrser/src/string.js~rsplit",
    "function/index.html#static-function-rsplit",
    "<span>rsplit</span> <span class=\"search-result-import-path\">nrser/src/string.js</span>",
    "function"
  ],
  [
    "nrser/src/metalogger/snapshot.js~snapshot",
    "function/index.html#static-function-snapshot",
    "<span>snapshot</span> <span class=\"search-result-import-path\">nrser/src/metalogger/snapshot.js</span>",
    "function"
  ],
  [
    "nrser/src/path.js~split",
    "function/index.html#static-function-split",
    "<span>split</span> <span class=\"search-result-import-path\">nrser/src/path.js</span>",
    "function"
  ],
  [
    "nrser/src/string.js~squish",
    "function/index.html#static-function-squish",
    "<span>squish</span> <span class=\"search-result-import-path\">nrser/src/string.js</span>",
    "function"
  ],
  [
    "nrser/src/types/struct.js~struct",
    "function/index.html#static-function-struct",
    "<span>struct</span> <span class=\"search-result-import-path\">nrser/src/types/struct.js</span>",
    "function"
  ],
  [
    "nrser/src/types/index.js~subclassof",
    "function/index.html#static-function-subclassOf",
    "<span>subclassOf</span> <span class=\"search-result-import-path\">nrser/src/types/index.js</span>",
    "function"
  ],
  [
    "nrser/src/index.js~t",
    "variable/index.html#static-variable-t",
    "<span>t</span> <span class=\"search-result-import-path\">nrser/src/index.js</span>",
    "variable"
  ],
  [
    "nrser/src/path.js~tabsdir",
    "variable/index.html#static-variable-tAbsDir",
    "<span>tAbsDir</span> <span class=\"search-result-import-path\">nrser/src/path.js</span>",
    "variable"
  ],
  [
    "nrser/src/path.js~tabspath",
    "variable/index.html#static-variable-tAbsPath",
    "<span>tAbsPath</span> <span class=\"search-result-import-path\">nrser/src/path.js</span>",
    "variable"
  ],
  [
    "nrser/src/path.js~tdir",
    "variable/index.html#static-variable-tDir",
    "<span>tDir</span> <span class=\"search-result-import-path\">nrser/src/path.js</span>",
    "variable"
  ],
  [
    "nrser/src/types/number.js~tinteger",
    "variable/index.html#static-variable-tInteger",
    "<span>tInteger</span> <span class=\"search-result-import-path\">nrser/src/types/number.js</span>",
    "variable"
  ],
  [
    "nrser/src/types/number.js~tnegative",
    "variable/index.html#static-variable-tNegative",
    "<span>tNegative</span> <span class=\"search-result-import-path\">nrser/src/types/number.js</span>",
    "variable"
  ],
  [
    "nrser/src/types/number.js~tnegativeinteger",
    "variable/index.html#static-variable-tNegativeInteger",
    "<span>tNegativeInteger</span> <span class=\"search-result-import-path\">nrser/src/types/number.js</span>",
    "variable"
  ],
  [
    "nrser/src/types/number.js~tnonnegativeinteger",
    "variable/index.html#static-variable-tNonNegativeInteger",
    "<span>tNonNegativeInteger</span> <span class=\"search-result-import-path\">nrser/src/types/number.js</span>",
    "variable"
  ],
  [
    "nrser/src/types/number.js~tnonpositiveinteger",
    "variable/index.html#static-variable-tNonPositiveInteger",
    "<span>tNonPositiveInteger</span> <span class=\"search-result-import-path\">nrser/src/types/number.js</span>",
    "variable"
  ],
  [
    "nrser/src/path.js~tnormdir",
    "variable/index.html#static-variable-tNormDir",
    "<span>tNormDir</span> <span class=\"search-result-import-path\">nrser/src/path.js</span>",
    "variable"
  ],
  [
    "nrser/src/path.js~tnormpath",
    "variable/index.html#static-variable-tNormPath",
    "<span>tNormPath</span> <span class=\"search-result-import-path\">nrser/src/path.js</span>",
    "variable"
  ],
  [
    "nrser/src/path.js~tpathsegment",
    "variable/index.html#static-variable-tPathSegment",
    "<span>tPathSegment</span> <span class=\"search-result-import-path\">nrser/src/path.js</span>",
    "variable"
  ],
  [
    "nrser/src/path.js~tpathsegments",
    "variable/index.html#static-variable-tPathSegments",
    "<span>tPathSegments</span> <span class=\"search-result-import-path\">nrser/src/path.js</span>",
    "variable"
  ],
  [
    "nrser/src/types/number.js~tpositive",
    "variable/index.html#static-variable-tPositive",
    "<span>tPositive</span> <span class=\"search-result-import-path\">nrser/src/types/number.js</span>",
    "variable"
  ],
  [
    "nrser/src/types/number.js~tpositiveinteger",
    "variable/index.html#static-variable-tPositiveInteger",
    "<span>tPositiveInteger</span> <span class=\"search-result-import-path\">nrser/src/types/number.js</span>",
    "variable"
  ],
  [
    "nrser/src/path.js~tresdir",
    "variable/index.html#static-variable-tResDir",
    "<span>tResDir</span> <span class=\"search-result-import-path\">nrser/src/path.js</span>",
    "variable"
  ],
  [
    "nrser/src/path.js~trespath",
    "variable/index.html#static-variable-tResPath",
    "<span>tResPath</span> <span class=\"search-result-import-path\">nrser/src/path.js</span>",
    "variable"
  ],
  [
    "nrser/src/path.js~ttildedir",
    "variable/index.html#static-variable-tTildeDir",
    "<span>tTildeDir</span> <span class=\"search-result-import-path\">nrser/src/path.js</span>",
    "variable"
  ],
  [
    "nrser/src/path.js~ttildepath",
    "variable/index.html#static-variable-tTildePath",
    "<span>tTildePath</span> <span class=\"search-result-import-path\">nrser/src/path.js</span>",
    "variable"
  ],
  [
    "nrser/src/types/type.js~ttype",
    "variable/index.html#static-variable-tType",
    "<span>tType</span> <span class=\"search-result-import-path\">nrser/src/types/type.js</span>",
    "variable"
  ],
  [
    "nrser/src/types/number.js~tzero",
    "variable/index.html#static-variable-tZero",
    "<span>tZero</span> <span class=\"search-result-import-path\">nrser/src/types/number.js</span>",
    "variable"
  ],
  [
    "nrser/src/string.js~tag",
    "function/index.html#static-function-tag",
    "<span>tag</span> <span class=\"search-result-import-path\">nrser/src/string.js</span>",
    "function"
  ],
  [
    "nrser/src/path.js~tildify",
    "variable/index.html#static-variable-tildify",
    "<span>tildify</span> <span class=\"search-result-import-path\">nrser/src/path.js</span>",
    "variable"
  ],
  [
    "nrser/src/path.js~todir",
    "function/index.html#static-function-toDir",
    "<span>toDir</span> <span class=\"search-result-import-path\">nrser/src/path.js</span>",
    "function"
  ],
  [
    "nrser/src/index.js~types",
    "variable/index.html#static-variable-types",
    "<span>types</span> <span class=\"search-result-import-path\">nrser/src/index.js</span>",
    "variable"
  ],
  [
    "nrser/src/path.js~untildify",
    "variable/index.html#static-variable-untildify",
    "<span>untildify</span> <span class=\"search-result-import-path\">nrser/src/path.js</span>",
    "variable"
  ],
  [
    "nrser/src/types/value.js~value",
    "function/index.html#static-function-value",
    "<span>value</span> <span class=\"search-result-import-path\">nrser/src/types/value.js</span>",
    "function"
  ],
  [
    "nrser/src/types/value.js~values",
    "function/index.html#static-function-values",
    "<span>values</span> <span class=\"search-result-import-path\">nrser/src/types/value.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "https://developer.mozilla.org/en/docs/Web/API/AudioContext",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "https://developer.mozilla.org/en-US/docs/Web/API/Element",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "https://developer.mozilla.org/en-US/docs/Web/API/Event",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "https://developer.mozilla.org/en-US/docs/Web/API/Node",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "https://developer.mozilla.org/en-US/docs/Web/API/NodeList",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/deferred.js",
    "file/src/Deferred.js.html",
    "src/Deferred.js",
    "file"
  ],
  [
    "src/deferred.js~deferred#constructor",
    "class/src/Deferred.js~Deferred.html#instance-constructor-constructor",
    "src/Deferred.js~Deferred#constructor",
    "method"
  ],
  [
    "src/deferred.js~deferred#promise",
    "class/src/Deferred.js~Deferred.html#instance-member-promise",
    "src/Deferred.js~Deferred#promise",
    "member"
  ],
  [
    "src/deferred.js~deferred#reject",
    "class/src/Deferred.js~Deferred.html#instance-member-reject",
    "src/Deferred.js~Deferred#reject",
    "member"
  ],
  [
    "src/deferred.js~deferred#resolve",
    "class/src/Deferred.js~Deferred.html#instance-member-resolve",
    "src/Deferred.js~Deferred#resolve",
    "member"
  ],
  [
    "src/array.js",
    "file/src/array.js.html",
    "src/array.js",
    "file"
  ],
  [
    "src/collection.js",
    "file/src/collection.js.html",
    "src/collection.js",
    "file"
  ],
  [
    "src/env.js",
    "file/src/env.js.html",
    "src/env.js",
    "file"
  ],
  [
    "src/errors/baseerror.js",
    "file/src/errors/BaseError.js.html",
    "src/errors/BaseError.js",
    "file"
  ],
  [
    "src/errors/keyerror.js",
    "file/src/errors/KeyError.js.html",
    "src/errors/KeyError.js",
    "file"
  ],
  [
    "src/errors/matcherror.js",
    "file/src/errors/MatchError.js.html",
    "src/errors/MatchError.js",
    "file"
  ],
  [
    "src/errors/notfounderror.js",
    "file/src/errors/NotFoundError.js.html",
    "src/errors/NotFoundError.js",
    "file"
  ],
  [
    "src/errors/notimplementederror.js",
    "file/src/errors/NotImplementedError.js.html",
    "src/errors/NotImplementedError.js",
    "file"
  ],
  [
    "src/errors/notimplementederror.js~notimplementederror.defaultmessage",
    "class/src/errors/NotImplementedError.js~NotImplementedError.html#static-member-defaultMessage",
    "src/errors/NotImplementedError.js~NotImplementedError.defaultMessage",
    "member"
  ],
  [
    "src/errors/nrsererror.js",
    "file/src/errors/NrserError.js.html",
    "src/errors/NrserError.js",
    "file"
  ],
  [
    "src/errors/stateerror.js",
    "file/src/errors/StateError.js.html",
    "src/errors/StateError.js",
    "file"
  ],
  [
    "src/errors/valueerror.js",
    "file/src/errors/ValueError.js.html",
    "src/errors/ValueError.js",
    "file"
  ],
  [
    "src/errors/index.js",
    "file/src/errors/index.js.html",
    "src/errors/index.js",
    "file"
  ],
  [
    "src/fs.js",
    "file/src/fs.js.html",
    "src/fs.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/lodash.js",
    "file/src/lodash.js.html",
    "src/lodash.js",
    "file"
  ],
  [
    "src/match.js",
    "file/src/match.js.html",
    "src/match.js",
    "file"
  ],
  [
    "src/metalogger/level.js",
    "file/src/metalogger/Level.js.html",
    "src/metalogger/Level.js",
    "file"
  ],
  [
    "src/metalogger/level.js~level#constructor",
    "class/src/metalogger/Level.js~Level.html#instance-constructor-constructor",
    "src/metalogger/Level.js~Level#constructor",
    "method"
  ],
  [
    "src/metalogger/level.js~level#name",
    "class/src/metalogger/Level.js~Level.html#instance-member-name",
    "src/metalogger/Level.js~Level#name",
    "member"
  ],
  [
    "src/metalogger/level.js~level#rank",
    "class/src/metalogger/Level.js~Level.html#instance-member-rank",
    "src/metalogger/Level.js~Level#rank",
    "member"
  ],
  [
    "src/metalogger/level.js~level.debug",
    "class/src/metalogger/Level.js~Level.html#static-member-DEBUG",
    "src/metalogger/Level.js~Level.DEBUG",
    "member"
  ],
  [
    "src/metalogger/level.js~level.error",
    "class/src/metalogger/Level.js~Level.html#static-member-ERROR",
    "src/metalogger/Level.js~Level.ERROR",
    "member"
  ],
  [
    "src/metalogger/level.js~level.fatal",
    "class/src/metalogger/Level.js~Level.html#static-member-FATAL",
    "src/metalogger/Level.js~Level.FATAL",
    "member"
  ],
  [
    "src/metalogger/level.js~level.info",
    "class/src/metalogger/Level.js~Level.html#static-member-INFO",
    "src/metalogger/Level.js~Level.INFO",
    "member"
  ],
  [
    "src/metalogger/level.js~level.levels",
    "class/src/metalogger/Level.js~Level.html#static-member-LEVELS",
    "src/metalogger/Level.js~Level.LEVELS",
    "member"
  ],
  [
    "src/metalogger/level.js~level.trace",
    "class/src/metalogger/Level.js~Level.html#static-member-TRACE",
    "src/metalogger/Level.js~Level.TRACE",
    "member"
  ],
  [
    "src/metalogger/level.js~level.warn",
    "class/src/metalogger/Level.js~Level.html#static-member-WARN",
    "src/metalogger/Level.js~Level.WARN",
    "member"
  ],
  [
    "src/metalogger/level.js~level.forname",
    "class/src/metalogger/Level.js~Level.html#static-method-forName",
    "src/metalogger/Level.js~Level.forName",
    "method"
  ],
  [
    "src/metalogger/levelspec.js",
    "file/src/metalogger/LevelSpec.js.html",
    "src/metalogger/LevelSpec.js",
    "file"
  ],
  [
    "src/metalogger/levelspec.js~levelspec#cache",
    "class/src/metalogger/LevelSpec.js~LevelSpec.html#instance-method-cache",
    "src/metalogger/LevelSpec.js~LevelSpec#cache",
    "method"
  ],
  [
    "src/metalogger/levelspec.js~levelspec#constructor",
    "class/src/metalogger/LevelSpec.js~LevelSpec.html#instance-constructor-constructor",
    "src/metalogger/LevelSpec.js~LevelSpec#constructor",
    "method"
  ],
  [
    "src/metalogger/levelspec.js~levelspec#content",
    "class/src/metalogger/LevelSpec.js~LevelSpec.html#instance-member-content",
    "src/metalogger/LevelSpec.js~LevelSpec#content",
    "member"
  ],
  [
    "src/metalogger/levelspec.js~levelspec#level",
    "class/src/metalogger/LevelSpec.js~LevelSpec.html#instance-member-level",
    "src/metalogger/LevelSpec.js~LevelSpec#level",
    "member"
  ],
  [
    "src/metalogger/levelspec.js~levelspec#match",
    "class/src/metalogger/LevelSpec.js~LevelSpec.html#instance-method-match",
    "src/metalogger/LevelSpec.js~LevelSpec#match",
    "method"
  ],
  [
    "src/metalogger/levelspec.js~levelspec#matchcontent",
    "class/src/metalogger/LevelSpec.js~LevelSpec.html#instance-method-matchContent",
    "src/metalogger/LevelSpec.js~LevelSpec#matchContent",
    "method"
  ],
  [
    "src/metalogger/levelspec.js~levelspec#matchpath",
    "class/src/metalogger/LevelSpec.js~LevelSpec.html#instance-method-matchPath",
    "src/metalogger/LevelSpec.js~LevelSpec#matchPath",
    "method"
  ],
  [
    "src/metalogger/levelspec.js~levelspec#path",
    "class/src/metalogger/LevelSpec.js~LevelSpec.html#instance-member-path",
    "src/metalogger/LevelSpec.js~LevelSpec#path",
    "member"
  ],
  [
    "src/metalogger/levelspec.js~levelspec#pathpattern",
    "class/src/metalogger/LevelSpec.js~LevelSpec.html#instance-member-pathPattern",
    "src/metalogger/LevelSpec.js~LevelSpec#pathPattern",
    "member"
  ],
  [
    "src/metalogger/levelspec.js~levelspec.minimatchize",
    "class/src/metalogger/LevelSpec.js~LevelSpec.html#static-method-minimatchize",
    "src/metalogger/LevelSpec.js~LevelSpec.minimatchize",
    "method"
  ],
  [
    "src/metalogger/logger.js",
    "file/src/metalogger/Logger.js.html",
    "src/metalogger/Logger.js",
    "file"
  ],
  [
    "src/metalogger/logger.js~logger#browserheaderformat",
    "class/src/metalogger/Logger.js~Logger.html#instance-member-browserHeaderFormat",
    "src/metalogger/Logger.js~Logger#browserHeaderFormat",
    "member"
  ],
  [
    "src/metalogger/logger.js~logger#constructor",
    "class/src/metalogger/Logger.js~Logger.html#instance-constructor-constructor",
    "src/metalogger/Logger.js~Logger#constructor",
    "method"
  ],
  [
    "src/metalogger/logger.js~logger#dateformat",
    "class/src/metalogger/Logger.js~Logger.html#instance-member-dateFormat",
    "src/metalogger/Logger.js~Logger#dateFormat",
    "member"
  ],
  [
    "src/metalogger/logger.js~logger#getconsolefunction",
    "class/src/metalogger/Logger.js~Logger.html#instance-method-getConsoleFunction",
    "src/metalogger/Logger.js~Logger#getConsoleFunction",
    "method"
  ],
  [
    "src/metalogger/logger.js~logger#getdelta",
    "class/src/metalogger/Logger.js~Logger.html#instance-method-getDelta",
    "src/metalogger/Logger.js~Logger#getDelta",
    "method"
  ],
  [
    "src/metalogger/logger.js~logger#lastmessagedate",
    "class/src/metalogger/Logger.js~Logger.html#instance-member-lastMessageDate",
    "src/metalogger/Logger.js~Logger#lastMessageDate",
    "member"
  ],
  [
    "src/metalogger/logger.js~logger#levelfor",
    "class/src/metalogger/Logger.js~Logger.html#instance-method-levelFor",
    "src/metalogger/Logger.js~Logger#levelFor",
    "method"
  ],
  [
    "src/metalogger/logger.js~logger#log",
    "class/src/metalogger/Logger.js~Logger.html#instance-method-log",
    "src/metalogger/Logger.js~Logger#log",
    "method"
  ],
  [
    "src/metalogger/logger.js~logger#loginbrowser",
    "class/src/metalogger/Logger.js~Logger.html#instance-method-logInBrowser",
    "src/metalogger/Logger.js~Logger#logInBrowser",
    "method"
  ],
  [
    "src/metalogger/logger.js~logger#loginnode",
    "class/src/metalogger/Logger.js~Logger.html#instance-method-logInNode",
    "src/metalogger/Logger.js~Logger#logInNode",
    "method"
  ],
  [
    "src/metalogger/logger.js~logger#nodeheaderformat",
    "class/src/metalogger/Logger.js~Logger.html#instance-member-nodeHeaderFormat",
    "src/metalogger/Logger.js~Logger#nodeHeaderFormat",
    "member"
  ],
  [
    "src/metalogger/logger.js~logger#notiftitle",
    "class/src/metalogger/Logger.js~Logger.html#instance-member-notifTitle",
    "src/metalogger/Logger.js~Logger#notifTitle",
    "member"
  ],
  [
    "src/metalogger/logger.js~logger#notify",
    "class/src/metalogger/Logger.js~Logger.html#instance-method-notify",
    "src/metalogger/Logger.js~Logger#notify",
    "method"
  ],
  [
    "src/metalogger/logger.js~logger#pushspec",
    "class/src/metalogger/Logger.js~Logger.html#instance-method-pushSpec",
    "src/metalogger/Logger.js~Logger#pushSpec",
    "method"
  ],
  [
    "src/metalogger/logger.js~logger#shouldlog",
    "class/src/metalogger/Logger.js~Logger.html#instance-method-shouldLog",
    "src/metalogger/Logger.js~Logger#shouldLog",
    "method"
  ],
  [
    "src/metalogger/logger.js~logger#specfor",
    "class/src/metalogger/Logger.js~Logger.html#instance-method-specFor",
    "src/metalogger/Logger.js~Logger#specFor",
    "method"
  ],
  [
    "src/metalogger/logger.js~logger#specs",
    "class/src/metalogger/Logger.js~Logger.html#instance-member-specs",
    "src/metalogger/Logger.js~Logger#specs",
    "member"
  ],
  [
    "src/metalogger/logger.js~logger#unshiftspec",
    "class/src/metalogger/Logger.js~Logger.html#instance-method-unshiftSpec",
    "src/metalogger/Logger.js~Logger#unshiftSpec",
    "method"
  ],
  [
    "src/metalogger/logger.js~logger.browser_colors",
    "class/src/metalogger/Logger.js~Logger.html#static-member-BROWSER_COLORS",
    "src/metalogger/Logger.js~Logger.BROWSER_COLORS",
    "member"
  ],
  [
    "src/metalogger/logger.js~logger.date_format_tokens",
    "class/src/metalogger/Logger.js~Logger.html#static-member-DATE_FORMAT_TOKENS",
    "src/metalogger/Logger.js~Logger.DATE_FORMAT_TOKENS",
    "member"
  ],
  [
    "src/metalogger/logger.js~logger.header_format_tokens",
    "class/src/metalogger/Logger.js~Logger.html#static-member-HEADER_FORMAT_TOKENS",
    "src/metalogger/Logger.js~Logger.HEADER_FORMAT_TOKENS",
    "member"
  ],
  [
    "src/metalogger/logger.js~logger.node_colors",
    "class/src/metalogger/Logger.js~Logger.html#static-member-NODE_COLORS",
    "src/metalogger/Logger.js~Logger.NODE_COLORS",
    "member"
  ],
  [
    "src/metalogger/logger.js~logger.format",
    "class/src/metalogger/Logger.js~Logger.html#static-method-format",
    "src/metalogger/Logger.js~Logger.format",
    "method"
  ],
  [
    "src/metalogger/logger.js~logger.formatdate",
    "class/src/metalogger/Logger.js~Logger.html#static-method-formatDate",
    "src/metalogger/Logger.js~Logger.formatDate",
    "method"
  ],
  [
    "src/metalogger/logger.js~logger.formatdelta",
    "class/src/metalogger/Logger.js~Logger.html#static-method-formatDelta",
    "src/metalogger/Logger.js~Logger.formatDelta",
    "method"
  ],
  [
    "src/metalogger/logger.js~logger.formatheader",
    "class/src/metalogger/Logger.js~Logger.html#static-method-formatHeader",
    "src/metalogger/Logger.js~Logger.formatHeader",
    "method"
  ],
  [
    "src/metalogger/logger.js~logger.formatlevel",
    "class/src/metalogger/Logger.js~Logger.html#static-method-formatLevel",
    "src/metalogger/Logger.js~Logger.formatLevel",
    "method"
  ],
  [
    "src/metalogger/logger.js~logger.formatpath",
    "class/src/metalogger/Logger.js~Logger.html#static-method-formatPath",
    "src/metalogger/Logger.js~Logger.formatPath",
    "method"
  ],
  [
    "src/metalogger/index.js",
    "file/src/metalogger/index.js.html",
    "src/metalogger/index.js",
    "file"
  ],
  [
    "src/metalogger/snapshot.js",
    "file/src/metalogger/snapshot.js.html",
    "src/metalogger/snapshot.js",
    "file"
  ],
  [
    "src/metalogger/snapshot.js~snapshot_ref#constructor",
    "class/src/metalogger/snapshot.js~SNAPSHOT_REF.html#instance-constructor-constructor",
    "src/metalogger/snapshot.js~SNAPSHOT_REF#constructor",
    "method"
  ],
  [
    "src/metalogger/snapshot.js~snapshot_ref#value",
    "class/src/metalogger/snapshot.js~SNAPSHOT_REF.html#instance-member-value",
    "src/metalogger/snapshot.js~SNAPSHOT_REF#value",
    "member"
  ],
  [
    "src/object.js",
    "file/src/object.js.html",
    "src/object.js",
    "file"
  ],
  [
    "src/path.js",
    "file/src/path.js.html",
    "src/path.js",
    "file"
  ],
  [
    "src/path.js~absdir",
    "typedef/index.html#static-typedef-AbsDir",
    "src/path.js~AbsDir",
    "typedef"
  ],
  [
    "src/path.js~abspath",
    "typedef/index.html#static-typedef-AbsPath",
    "src/path.js~AbsPath",
    "typedef"
  ],
  [
    "src/path.js~dir",
    "typedef/index.html#static-typedef-Dir",
    "src/path.js~Dir",
    "typedef"
  ],
  [
    "src/path.js~normdir",
    "typedef/index.html#static-typedef-NormDir",
    "src/path.js~NormDir",
    "typedef"
  ],
  [
    "src/path.js~normpath",
    "typedef/index.html#static-typedef-NormPath",
    "src/path.js~NormPath",
    "typedef"
  ],
  [
    "src/path.js~pathsegment",
    "typedef/index.html#static-typedef-PathSegment",
    "src/path.js~PathSegment",
    "typedef"
  ],
  [
    "src/path.js~pathsegments",
    "typedef/index.html#static-typedef-PathSegments",
    "src/path.js~PathSegments",
    "typedef"
  ],
  [
    "src/path.js~resdir",
    "typedef/index.html#static-typedef-ResDir",
    "src/path.js~ResDir",
    "typedef"
  ],
  [
    "src/path.js~resolvedpath",
    "typedef/index.html#static-typedef-ResolvedPath",
    "src/path.js~ResolvedPath",
    "typedef"
  ],
  [
    "src/path.js~tildedir",
    "typedef/index.html#static-typedef-TildeDir",
    "src/path.js~TildeDir",
    "typedef"
  ],
  [
    "src/path.js~tildepath",
    "typedef/index.html#static-typedef-TildePath",
    "src/path.js~TildePath",
    "typedef"
  ],
  [
    "src/print.js",
    "file/src/print.js.html",
    "src/print.js",
    "file"
  ],
  [
    "src/string.js",
    "file/src/string.js.html",
    "src/string.js",
    "file"
  ],
  [
    "src/testing/describer.js",
    "file/src/testing/Describer.js.html",
    "src/testing/Describer.js",
    "file"
  ],
  [
    "src/testing/describer.js~describer#class",
    "class/src/testing/Describer.js~Describer.html#instance-method-class",
    "src/testing/Describer.js~Describer#class",
    "method"
  ],
  [
    "src/testing/describer.js~describer#constructor",
    "class/src/testing/Describer.js~Describer.html#instance-constructor-constructor",
    "src/testing/Describer.js~Describer#constructor",
    "method"
  ],
  [
    "src/testing/describer.js~describer#file",
    "class/src/testing/Describer.js~Describer.html#instance-method-file",
    "src/testing/Describer.js~Describer#file",
    "method"
  ],
  [
    "src/testing/describer.js~describer#packageroot",
    "class/src/testing/Describer.js~Describer.html#instance-member-packageRoot",
    "src/testing/Describer.js~Describer#packageRoot",
    "member"
  ],
  [
    "src/testing/index.js",
    "file/src/testing/index.js.html",
    "src/testing/index.js",
    "file"
  ],
  [
    "src/testing/index.js~expect#constructor",
    "class/src/testing/index.js~Expect.html#instance-constructor-constructor",
    "src/testing/index.js~Expect#constructor",
    "method"
  ],
  [
    "src/testing/index.js~expect#instanceof",
    "class/src/testing/index.js~Expect.html#instance-member-instanceOf",
    "src/testing/index.js~Expect#instanceOf",
    "member"
  ],
  [
    "src/testing/index.js~expect#lengthof",
    "class/src/testing/index.js~Expect.html#instance-member-lengthOf",
    "src/testing/index.js~Expect#lengthOf",
    "member"
  ],
  [
    "src/testing/index.js~expect#props",
    "class/src/testing/index.js~Expect.html#instance-member-props",
    "src/testing/index.js~Expect#props",
    "member"
  ],
  [
    "src/testing/index.js~expect#size",
    "class/src/testing/index.js~Expect.html#instance-member-size",
    "src/testing/index.js~Expect#size",
    "member"
  ],
  [
    "src/testing/index.js~expect#test",
    "class/src/testing/index.js~Expect.html#instance-method-test",
    "src/testing/index.js~Expect#test",
    "method"
  ],
  [
    "src/types/collection.js",
    "file/src/types/collection.js.html",
    "src/types/collection.js",
    "file"
  ],
  [
    "src/types/collection.js~keypath",
    "typedef/index.html#static-typedef-KeyPath",
    "src/types/collection.js~KeyPath",
    "typedef"
  ],
  [
    "src/types/index.js",
    "file/src/types/index.js.html",
    "src/types/index.js",
    "file"
  ],
  [
    "src/types/list.js",
    "file/src/types/list.js.html",
    "src/types/list.js",
    "file"
  ],
  [
    "src/types/number.js",
    "file/src/types/number.js.html",
    "src/types/number.js",
    "file"
  ],
  [
    "src/types/number.js~integer",
    "typedef/index.html#static-typedef-Integer",
    "src/types/number.js~Integer",
    "typedef"
  ],
  [
    "src/types/number.js~negativeinteger",
    "typedef/index.html#static-typedef-NegativeInteger",
    "src/types/number.js~NegativeInteger",
    "typedef"
  ],
  [
    "src/types/number.js~nonnegativeinteger",
    "typedef/index.html#static-typedef-NonNegativeInteger",
    "src/types/number.js~NonNegativeInteger",
    "typedef"
  ],
  [
    "src/types/number.js~nonpositiveinteger",
    "typedef/index.html#static-typedef-NonPositiveInteger",
    "src/types/number.js~NonPositiveInteger",
    "typedef"
  ],
  [
    "src/types/number.js~positive",
    "typedef/index.html#static-typedef-Positive",
    "src/types/number.js~Positive",
    "typedef"
  ],
  [
    "src/types/number.js~positiveinteger",
    "typedef/index.html#static-typedef-PositiveInteger",
    "src/types/number.js~PositiveInteger",
    "typedef"
  ],
  [
    "src/types/number.js~positiveinteger",
    "typedef/index.html#static-typedef-PositiveInteger",
    "src/types/number.js~PositiveInteger",
    "typedef"
  ],
  [
    "src/types/number.js~zero",
    "typedef/index.html#static-typedef-Zero",
    "src/types/number.js~Zero",
    "typedef"
  ],
  [
    "src/types/string.js",
    "file/src/types/string.js.html",
    "src/types/string.js",
    "file"
  ],
  [
    "src/types/struct.js",
    "file/src/types/struct.js.html",
    "src/types/struct.js",
    "file"
  ],
  [
    "src/types/type.js",
    "file/src/types/type.js.html",
    "src/types/type.js",
    "file"
  ],
  [
    "src/types/type.js~type",
    "typedef/index.html#static-typedef-Type",
    "src/types/type.js~Type",
    "typedef"
  ],
  [
    "src/types/value.js",
    "file/src/types/value.js.html",
    "src/types/value.js",
    "file"
  ]
]